### ISSUE TITLE
vscode extention NASM highlighting problem

### ISSUE THREAD

**Issue by yuval-steuer** [13xforever/x86-assembly-textmate-bundle#12]
The vscode "x86 and x86_64 Assembly" extention seems to not highlight certain keywords on asm , and nasm files. 
for instance : 
global , 
section , 
etc...
However in the photo about vscode, global and section are clearly highlighted in lightblue. 
This raises the suspesion that the vscode extention in the vscode market place needs some updating and is not on par with the github version here. 
Thanks! great work!

**Comment by 13xforever** [comment]
VS Code and Atom syntax highlighting is based on an older TextMate grammar format, which is limited and very hard to work correctly.

Sublime Text 3 introduced a newer, more flexible grammar engine which allowed a full grammar rewrite that follows the specs much more closely, and works almost perfectly.

Unfortunately, there's no easy way to backport it to older format, and thus vs code and atom will be limited in what they can highlight until either:
* they'll support newer grammar declaration
* there'll be a tool that would transform newer grammar to older format (see issue #11)
* or someone will write a full language service

personally, I wouldn't hold my breath for any of this.
