### ISSUE TITLE
VS code unable to build nasm code

### ISSUE THREAD

**Issue by Furqan136** [13xforever/x86-assembly-textmate-bundle#13]
With Sublime Text 3, I edited NASM.sublime-build file and added
`
{
 	"cmd": ["nasm", "-f", "bin", "${file}","-l", "${file_base_name}.lst" , "-o", "${file_base_name}.com"],
    "file_regex": "^(..[^:]*):([0-9]+):?([0-9]+)?:? (.*)$",
    "working_dir": "${file_path}"
}

`
This made ST3 build my .asm files and highlight errors. I need to do the same for vscode version of this extension but I can't figure it out. Can you suggest  solution.

**Comment by 13xforever** [comment]
You'll have to write an appropriate build task, documentation is available at vscode website: https://code.visualstudio.com/docs/editor/tasks
