### ISSUE TITLE
xmm16-31 and ymm16-31 registers not formatted

### ISSUE THREAD

**Issue by travisdowns** [13xforever/x86-assembly-textmate-bundle#16]
The syntax highlighter doesn't seem to know that `xmm` and `ymm` registers go up to 31 now, just like `zmm` with AVX-512:

![image](https://user-images.githubusercontent.com/2403521/72939352-b5759180-3d3a-11ea-9f62-acf58d14e725.png)

**Comment by 13xforever** [comment]
This was fixed in the v3 rewrite for sublime text, and atom/vscode are still waiting for the mythic backport in #11

**Comment by 13xforever** [comment]
should be fixed with the v2.3.0 update released today
