### ISSUE TITLE
Bug when formatting line comment

### ISSUE THREAD

**Issue by Haltarys** [13xforever/x86-assembly-textmate-bundle#17]
When the following code is saved, an extra space is added before each semi-colon. This happens EVERY TIME the file is saved.
```asm
mov rax, 0 ; blah blah
           ; line comment
```

For example, when I save 3 times in a row, I get
```asm
mov rax, 0    ; blah blah
              ; line comment
```

**Comment by 13xforever** [comment]
This package only provides highlighting. There's no language server, type checker, or coder formatter of any kind. It literally just a YAML file.
