### ISSUE TITLE
Add support to NASM %idefine

### ISSUE THREAD

**Issue by qodroi** [13xforever/x86-assembly-textmate-bundle#23]
I could send a patch myself but the code is quite a mess, and multiple reminders for single-line macros exist. `nasm` also has `%idefine` single-line macro that defines a case-insensitive macro, and not having it supported, thus not colored, somehow bothers me.. Would it be possible to support it as well?

Thanks!

**Comment by 13xforever** [comment]
I'll look into it as soon as I have some free time, but it's hard to come by recently.

**Comment by Super-Pizza** [comment]
There's another uncolored keyword: `%rotate`

**Comment by Super-Pizza** [comment]
I made a fix here: #24

**Comment by 13xforever** [comment]
I pushed an update tag, so it will be shortly available via sublime package control. I'll push the update to vscode a bit later when my update branch is ready.

**Comment by 13xforever** [comment]
Should be live on visual studio marketplace for vscode as well
