### ISSUE TITLE
建议添加

### ISSUE THREAD

**Issue by NERD-k** [13xforever/x86-assembly-textmate-bundle#9]
添加这一句 `<string>A51</string> 		<!-- Keil自动添加的启动函数 -->`

‘.A51’文件是Keil创建51单片机项目时会自动添加的汇编语言的文件，希望添加支持；
汇编的关键词时大小写不敏感的，希望能够同时支持大写写的汇编语句

**Comment by 13xforever** [comment]
Regrettably I do not speak Chinese, but if this is yet another request for case sensitivity, see #6.

**Comment by NERD-k** [comment]
Sorry, my native language is chinese so I speak Chinese as usual, I can speak English but bot good.
I suggest to add this line `<string>A51</string> <!-- The function file which Keil auto add -->`

` .A51 ` file wiil be auto add to  the MCS-51 project created by Keil 5, wish ` .A51 ` file can be support well.
The key word of ASM is not sensitive to uppercase and lowercase, so it is the more friendly if this support to uppercase and lowercase.

**Comment by NERD-k** [comment]
![sublime_text_2017-11-21_17-39-08](https://user-images.githubusercontent.com/28424691/33065145-033b3564-cee3-11e7-8832-610a8983ba51.png)

**Comment by 13xforever** [comment]
This is a 8051 arch, not Intel x86_64. It needs a different syntax highlighter.
